version: '3.3'
services:
  app:
    container_name: 'python3'
    build: . # ComposeFileを実行し、ビルドされるときのpath
    tty: true
    ports:
      - '3000:3000' # ホスト側のポート：コンテナのポート
    volumes:
      - ../app:/app # ホスト側のappをコンテナのappにマウント
      - ~/.config/pulse:/root/.config/pulse
    working_dir: /app # 起動時のカレントフォルダ
    environment:
      - PULSE_SERVER=docker.for.mac.localhost
