version: '3'
services:
  app:
    # コンテナ名
    container_name: 'python3'
    # ComposeFileを実行し、ビルドされるときのpath
    build: .
    tty: true
    # ホスト側のポート：コンテナのポート
    ports:
      - '3000:3000'
    # ホスト側のappをコンテナのappにマウント
    volumes:
      - ../app:/app
    # 起動時のカレントフォルダ
    working_dir: /app
